config/routes.rb
CloudStory::Application.routes.draw do
  resources :clips

  root :to => "home#index"

  devise_for :users

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/clip.rb
class Clip < ActiveRecord::Base
  attr_accessible :character_id, :content, :state, :take_id, :trim_end, :trim_start, :user_id
end

app/models/dialogue.rb
class Dialogue < ActiveRecord::Base
  attr_accessible :content, :scene_id
end

app/models/role.rb
class Role < ActiveRecord::Base
  attr_accessible :name
end

app/models/scene.rb
class Scene < ActiveRecord::Base
  attr_accessible :child_id, :description, :parent_id, :story_id, :title
end

app/models/story.rb
class Story < ActiveRecord::Base
  attr_accessible :title, :user_id
end

app/models/story_user.rb
class StoryUser < ActiveRecord::Base
  attr_accessible :story_id, :user_id
end

app/models/storyline.rb
class Storyline < ActiveRecord::Base
  attr_accessible :child_id, :clip_id, :parent_id, :story_id
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

end

app/controllers/clips_controller.rb
class ClipsController < InheritedResources::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clips_helper.rb
module ClipsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/clips/_form.html.erb
<%= form_for(@clip) do |f| %>
  <% if @clip.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@clip.errors.count, "error") %> prohibited this clip from being saved:</h2>

      <ul>
      <% @clip.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :take_id %><br />
    <%= f.number_field :take_id %>
  </div>
  <div class="field">
    <%= f.label :character_id %><br />
    <%= f.number_field :character_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :trim_start %><br />
    <%= f.time_select :trim_start %>
  </div>
  <div class="field">
    <%= f.label :trim_end %><br />
    <%= f.time_select :trim_end %>
  </div>
  <div class="field">
    <%= f.label :state %><br />
    <%= f.text_field :state %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/clips/edit.html.erb
<h1>Editing clip</h1>

<%= render 'form' %>

<%= link_to 'Show', @clip %> |
<%= link_to 'Back', clips_path %>

app/views/clips/index.html.erb
<h1>Listing clips</h1>

<table>
  <tr>
    <th>Take</th>
    <th>Character</th>
    <th>User</th>
    <th>Content</th>
    <th>Trim start</th>
    <th>Trim end</th>
    <th>State</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @clips.each do |clip| %>
  <tr>
    <td><%= clip.take_id %></td>
    <td><%= clip.character_id %></td>
    <td><%= clip.user_id %></td>
    <td><%= clip.content %></td>
    <td><%= clip.trim_start %></td>
    <td><%= clip.trim_end %></td>
    <td><%= clip.state %></td>
    <td><%= link_to 'Show', clip %></td>
    <td><%= link_to 'Edit', edit_clip_path(clip) %></td>
    <td><%= link_to 'Destroy', clip, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Clip', new_clip_path %>

app/views/clips/new.html.erb
<h1>New clip</h1>

<%= render 'form' %>

<%= link_to 'Back', clips_path %>

app/views/clips/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Take:</b>
  <%= @clip.take_id %>
</p>

<p>
  <b>Character:</b>
  <%= @clip.character_id %>
</p>

<p>
  <b>User:</b>
  <%= @clip.user_id %>
</p>

<p>
  <b>Content:</b>
  <%= @clip.content %>
</p>

<p>
  <b>Trim start:</b>
  <%= @clip.trim_start %>
</p>

<p>
  <b>Trim end:</b>
  <%= @clip.trim_end %>
</p>

<p>
  <b>State:</b>
  <%= @clip.state %>
</p>


<%= link_to 'Edit', edit_clip_path(@clip) %> |
<%= link_to 'Back', clips_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CloudStory</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>